### ISSUE TITLE
青青爬

### ISSUE THREAD

**Issue by botax-issue** [zz5840/test#10]
## Description / 问题描述
爬爬爬爬
## How to Reproduce / 如何复现
一直复现
## Device Info / 设备信息
地球ol v0.000000001

---
Sender Platform: `QQ`
Sender ID: `2221697258`

**Comment by zz5840** [comment]
![screenshot](https://i.loli.net/2020/04/07/FamxtB1AoCKNGfn.jpg)

**Comment by zz5840** [comment]
![screenshot](https://i.loli.net/2020/04/07/FamxtB1AoCKNGfn.jpg)
