### ISSUE TITLE
啊哈哈

### ISSUE THREAD

**Issue by botax-issue** [zz5840/test#14]
## Description / 问题描述
啊
## How to Reproduce / 如何复现
啊
## Device Info / 设备信息
啊
## Screenshots / 屏幕截图
![pic](https://i.loli.net/2020/04/07/lqO4xmnby7SQFke.gif)
---
Sender Platform: `${PlatformName[this.message.platform][2]}`
Sender ID: `${this.message.user.id}`

**Comment by zz5840** [comment]
挺好

**Comment by zz5840** [comment]
gkd

**Comment by zz5840** [comment]
摸了摸了
