### ISSUE TITLE
[1.12.2]114514

### ISSUE THREAD

**Issue by botax-issue** [zz5840/test#42]
## 反馈模组

i18n

## 问题描述

1919

## 游戏版本

1.12.2

***

Sender Platform: Discord

Sender ID: 412860058968260609

**Comment by botax-issue** [comment]
114514
***
`Sender Platform: Discord`
`Sender ID: 383568512825819156`

**Comment by zz5840** [comment]
11111

**Comment by botax-issue** [comment]
1221212121212
***
`Sender Platform: Discord`
`Sender ID: 383568512825819156`

**Comment by botax-issue** [comment]
dedededededed
***
`Sender Platform: Discord`
`Sender ID: 383568512825819156`

**Comment by botax-issue** [comment]
swe2de3w
***
`Sender Platform: Discord`
`Sender ID: 383568512825819156`

**Comment by zz5840** [comment]
hahahha

**Comment by zz5840** [comment]
sedwerfewrfwefwre

**Comment by zz5840** [comment]
ssssssssssss

**Comment by zz5840** [comment]
dewdedwecrts

**Comment by zz5840** [comment]
111111111111111111111

**Comment by zz5840** [comment]
1212121212121212
